repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v12.0.1
    hooks:
      - id: clang-format
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        args: [-checks=clang-diagnostic-return-type]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
