cc_binary(
    name = "remove_duplicates",
    srcs = ["remove_duplicates.cpp"],
    deps = [
        "//cci:utils",
    ],
)

cc_binary(
    name = "kth_element",
    srcs = ["kth_element.cpp"],
    deps = [
        "//cci:utils",
    ],
)

cc_binary(
    name = "delete_middle",
    srcs = ["delete_middle.cpp"],
    deps = [
        "//cci:utils",
    ],
)

cc_binary(
    name = "partition",
    srcs = ["partition.cpp"],
    deps = [
        "//cci:utils",
    ],
)

cc_binary(
    name = "sum_lists",
    srcs = ["sum_lists.cpp"],
    deps = [
        "//cci:utils",
    ],
)

cc_binary(
    name = "palindrome",
    srcs = ["palindrome.cpp"],
    deps = [
        "//cci:utils",
    ],
)

cc_binary(
    name = "intersection",
    srcs = ["intersection.cpp"],
)

cc_binary(
    name = "loop",
    srcs = ["loop.cpp"],
)
