cc_binary(
    name = "min_elem",
    srcs = ["min_elem.cpp"],
)

cc_binary(
    name = "stacks_of_plates",
    srcs = ["stacks_of_plates.cpp"],
)

cc_binary(
    name = "queue_via_stack",
    srcs = ["queue_via_stack.cpp"],
)
