cc_binary(
    name = "unique",
    srcs = [
        "unique.cpp"
    ],
)

cc_binary(
    name = "permutation",
    srcs = [
        "permutation.cpp"
    ],
)

cc_binary(
    name = "urlify",
    srcs = [
        "urlify.cpp"
    ]
)

cc_binary(
    name = "palindrome",
    srcs = [
        "palindrome.cpp"
    ]
)

cc_binary(
    name = "one_away",
    srcs = [
        "one_away.cpp"
    ]
)

cc_binary(
    name = "string_compression",
    srcs = [
        "string_compression.cpp"
    ]
)

cc_binary(
    name = "rotate_matrix",
    srcs = [
        "rotate_matrix.cpp"
    ]
)

cc_binary(
    name = "zero_matrix",
    srcs = [
        "zero_matrix.cpp"
    ]
)
